name: CI to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Build & Push Angular Client
      - name: Build and push ClientApp
        uses: docker/build-push-action@v6
        with:
          context: ./ClientApp
          file: ./ClientApp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angular-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 2. Build & Push .NET Web API
      - name: Build and push WebApiRestful
        uses: docker/build-push-action@v6
        with:
          context: ./WebApiRestful
          file: ./WebApiRestful/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapicore-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
